name: Build

env:
  NODE_VERSION: 24
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    defaults:
      run:
        working-directory: ./sheet

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Dependency Init
        run: npm install --legacy-peer-deps

      - name: npm React
        run: npm run build

      - name: npm Electron
        run: npx electron-builder --publish=never

      - name: Remove existing release assets
        uses: actions/github-script@v7
        with:
          script: |
            const tag = process.env.GITHUB_REF_NAME
            const { owner, repo } = context.repo
            const release = await github.rest.repos.getReleaseByTag({ owner, repo, tag })
            const assets = release.data.assets || []
            for (const asset of assets) {
              await github.rest.repos.deleteReleaseAsset({
                owner,
                repo,
                asset_id: asset.id,
              })
            }

      - name: Upload assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          overwrite_files: true
          files: |
            sheet/release/**/*Setup*.exe
            sheet/release/**/*.dmg
            sheet/release/**/*.AppImage
